import time
import random
import requests
import argparse

# Configuration
API_URL = "http://localhost:8000/api/v1"

class AutonomousWorker:
    def __init__(self, name: str, interval: int = 5):
        self.name = name
        self.interval = interval
        self.kin_id = None
        
    def authenticate(self):
        """Get or create Kin Profile ID."""
        print(f"[{self.name}] Authenticating...")
        try:
            response = requests.get(f"http://localhost:8000/debug/kin-profile")
            if response.status_code == 200:
                self.kin_id = response.json().get("kin_id")
                print(f"[{self.name}] Authenticated with Kin ID: {self.kin_id}")
            else:
                print(f"[{self.name}] Auth Failed: {response.text}")
                exit(1)
        except Exception as e:
            print(f"[{self.name}] Connection Error: {e}")
            exit(1)

    def find_and_do_work(self):
        """Find open tasks and perform them."""
        try:
            # 1. List Tasks
            response = requests.get(f"{API_URL}/tasks")
            if response.status_code != 200:
                print(f"[{self.name}] Failed to fetch tasks")
                return

            tasks = response.json()
            open_tasks = [t for t in tasks if t.get('status') == 'OPEN'] # API filters OPEN by default mostly
            
            if not open_tasks:
                print(f"[{self.name}] No tasks found. Resting...")
                return

            # Pick one task
            task = random.choice(open_tasks)
            print(f"[{self.name}] Found Task: {task['title']} (${task['budget']})")
            
            # 2. Claim Task
            self.claim_task(task['id'])
            
            # 3. Simulate Work
            work_duration = random.randint(2, 5)
            print(f"[{self.name}] Working on task for {work_duration}s...")
            time.sleep(work_duration)
            
            # 4. Submit Proof
            proof = f"Completed request: {task['title']}\nGenerated by Auto-Worker."
            self.submit_proof(task['id'], proof)
            
        except Exception as e:
            print(f"[{self.name}] Error in loop: {e}")

    def claim_task(self, task_id):
        try:
            response = requests.post(
                f"{API_URL}/tasks/{task_id}/claim",
                json={"kin_id": self.kin_id}
            )
            if response.status_code == 200:
                print(f"[{self.name}] Claimed Task {task_id}")
            else:
                print(f"[{self.name}] Claim Failed: {response.text}")
        except Exception as e:
            print(f"[{self.name}] Claim Error: {e}")

    def submit_proof(self, task_id, proof):
        try:
            response = requests.post(
                f"{API_URL}/tasks/{task_id}/submit",
                json={"proof": proof}
            )
            if response.status_code == 200:
                print(f"[{self.name}] Submitted Work for Task {task_id}")
            else:
                print(f"[{self.name}] Submission Failed: {response.text}")
        except Exception as e:
            print(f"[{self.name}] Submission Error: {e}")

    def run_loop(self):
        """Main loop."""
        self.authenticate()
        print(f"[{self.name}] Starting Worker Loop (Interval: {self.interval}s)...")
        print("Press Ctrl+C to stop.")
        
        try:
            while True:
                self.find_and_do_work()
                time.sleep(self.interval)
        except KeyboardInterrupt:
            print(f"\n[{self.name}] Stopping...")

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="AgentKin Autonomous Worker")
    parser.add_argument("--interval", type=int, default=5, help="Seconds between checks")
    args = parser.parse_args()
    
    worker = AutonomousWorker("Worker-Bot-01", interval=args.interval)
    worker.run_loop()
